#!/usr/bin/env node

/**
 * Gemini API Setup Script
 *
 * This script helps users set up their Google Gemini API key for the Quizzard app.
 * It creates the .env file with the proper configuration.
 */

const fs = require("fs");
const path = require("path");
const readline = require("readline");

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

console.log("🧠 Quizzard - Gemini API Setup");
console.log("================================\n");

console.log(
  "To use AI-powered question generation, you need a Google Gemini API key."
);
console.log(
  "📝 Get your free API key at: https://makersuite.google.com/app/apikey\n"
);

rl.question("Enter your Gemini API key: ", (apiKey) => {
  if (!apiKey || apiKey.trim() === "") {
    console.log("❌ No API key provided. Setup cancelled.");
    rl.close();
    return;
  }

  const envContent = `# Google Gemini API Configuration
# Generated by setup script on ${new Date().toISOString()}
VITE_GEMINI_API_KEY=${apiKey.trim()}

# API Information:
# - Free tier: 15 requests/minute, 1M tokens/day
# - Perfect for personal use and small teams
# - Get your key at: https://makersuite.google.com/app/apikey
`;

  const envPath = path.join(process.cwd(), ".env");

  try {
    fs.writeFileSync(envPath, envContent);
    console.log("\n✅ API key configured successfully!");
    console.log("📁 Created .env file with your Gemini API key");
    console.log("\n🚀 You can now run: npm run dev");
    console.log("🌐 The app will be available at: http://localhost:5173");
    console.log("\n💡 Features available:");
    console.log("   • AI question generation in English & Bulgarian");
    console.log("   • Difficulty levels: Easy, Medium, Hard");
    console.log("   • Custom categories or random topics");
    console.log("   • Online/offline detection");
  } catch (error) {
    console.log("❌ Error creating .env file:", error.message);
  }

  rl.close();
});

rl.on("close", () => {
  console.log("\n👋 Setup complete! Happy quizzing!");
  process.exit(0);
});
